kind: Service
apiVersion: v1
metadata:
  name: minecraft-server-py
spec:
  selector:
    app: minecraft-server-py
  ports:
  - name: server
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
