apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraft-0000
  namespace: minecraft
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        env:
        - name: EULA
          value: "true"
        ports:
        - containerPort: 25565
          name: server
        - containerPort: 25575
          name: arcon
        volumeMounts:
        - mountPath: "/data"
          name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azure-managed-disk
